var NAVTREEINDEX0 =
{
"enum-sample.html":[7,1],
"im0001.html":[5,0],
"im0001.html#supported-property-types":[5,0,0],
"im0002.html":[5,1],
"index.html":[],
"index.html#diagnostics":[1],
"index.html#documentation":[4],
"index.html#how-to-use":[2],
"index.html#overview":[0],
"index.html#sample":[3],
"md_ImmutableAnalyzer_2ImmutableAnalyzer_2doc_2diagnostics.html":[5],
"md_ImmutableAnalyzer_2ImmutableAnalyzer_2doc_2how-to-use.html":[6],
"pages.html":[],
"samples.html":[7],
"samples.html#example-with-built-in-types":[7,0],
"user-defined-types.html":[7,2]
};
