name: Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: 'doc'
          doxyfile-path: 'Doxyfile'
