# This is a basic workflow to help you get started with Actions

name: Doxygen

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Doxygenize
        uses: langroodi/doxygenize@v1.7.0
        with:
          doxygenconf: "doc/Doxyfile"
          htmloutput: "html"
          
          
