name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout  
      uses: actions/checkout@v1
      
    - name: setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: restore
      run: dotnet restore

    - name: test
      run: dotnet test --logger "trx;LogFileName=test-results.trx" || true

    - name: test report
      uses: dorny/test-reporter@v1
      id: test_report
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true

    - name: update README.md
      run: sed -i '2s/.*/[![Tests](https:\/\/github.com\/protomorphine\/ImmutableAnalyzer\/actions\/workflows\/test-report.yaml\/badge.svg)](${{ toJSON(steps.test_report.outputs.url_html) }})/' README.md

    - name: add & commit
      uses: EndBug/add-and-commit@v9
      with:
          add: README.md
          message: 'update test badge in README.md'
          default_author: github_action
          fetch: false
