name: Tests

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/**'
      - 'doc/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.github/**'
      - 'doc/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout  
      uses: actions/checkout@v2
      
    - name: setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: restore
      run: dotnet restore

    - name: test
      run: dotnet test --logger "trx;LogFileName=test-results.trx" || true

    - name: create test report
      uses: dorny/test-reporter@v1
      id: test_report
      if: always()
      with:
        name: Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true

    - name: update test badge in README.md
      run: |
        echo "Adding test report to README.md file..."
        
        test_report_url=$(echo ${{ toJson(steps.test_report.outputs.url_html) }} | sed 's/\//\\\//g')
        workflow_path=$(echo ${{github.workflow_ref}} | sed 's/@.*//')
        badge_url=$(echo "https://github.com/protomorphine/ImmutableAnalyzer/actions/workflows/test-report.yaml/badge.svg" | sed 's/\//\\\//g')
        
        echo "Badge URL: $badge_url"
        echo "Workflow Path: $workflow_path"
        echo "Workflow Ref ${{ github.workflow_ref }}"
        echo "Report URL: $test_report_url"
        
        sed -i '2s/.*/[![Tests]('"$badge_url"')]('"$test_report_url"')/' README.md

    - name: commit changes
      uses: EndBug/add-and-commit@v9
      with:
          add: README.md
          message: 'update test badge in README.md'
          default_author: github_actions
          fetch: false
